export const UPDATE_POSTS = 'UPDATE_POSTS';

// LOGIN ACTION TYPES
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// TOKEN PERSISTENT
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const LOGOUT = 'LOGOUT';


// SIGNUP ACTION TYPES  
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';

// EDIT USER TYPES
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL';

// USER PROFILE
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'; 
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'; 
export const FETCH_USER_PROFILE_START = 'FETCH_USER_PROFILE_START'; 

// FRIENDS
export const FETCH_USER_FRIEND = 'FETCH_USER_FRIEND'; 
export const ADD_FRIEND = 'ADD_FRIEND'; 
export const REMOVE_FRIEND = 'REMOVE_FRIEND'; 